"""Netlist export formats used by fabricators and bare-board testers.

We support IPC-D-356A — the industry-standard bare-board test netlist.
"""


def write_ipc_d_356a(board, path):
    """Write an IPC-D-356A netlist for bare-board testing.

    Each line is a 'midpoint' record describing a pad or via with its net,
    layer, and coordinates (in 1/10 mil).
    """
    if board.netlist is None:
        raise ValueError("board has no associated netlist")
    lines = []
    lines.append("C  IPC-D-356A bare-board test netlist")
    lines.append("C  Generated by CircuitForge")
    lines.append("P  JOB    " + board.title)
    lines.append("P  UNITS  METRIC")

    def emit(net, ref, pin, x, y, layer, drill):
        # net (14 chars), then designator, pin, A code, X, Y, layer
        # We use record type 317 (midpoint) — simplified.
        n = (net or "$NONE$").ljust(14)
        des = (ref or "?").ljust(6)
        p = (str(pin) if pin else "1").ljust(4)
        x_um = int(round(x * 1000))
        y_um = int(round(y * 1000))
        access = "A02" if layer.endswith("B.Cu") else "A01"
        line = (f"317{n}{des}-{p}D{int(drill*1000):04d}PA00X{x_um:+07d}Y{y_um:+07d}{access}")
        lines.append(line)

    for fpi in board.placements:
        for pad in fpi.footprint.pads:
            net = pad.net
            if net is None:
                # try to look up via netlist
                node = None
                for n in board.netlist._nodes.values():
                    if (fpi.ref, pad.name) in n.pins:
                        node = n; break
                net = node.name if node else None
            emit(net, fpi.ref, pad.name,
                 fpi.x + pad.x, fpi.y + pad.y,
                 pad.layer, pad.drill_diameter)

    for v in board.vias:
        emit(v.net, "VIA", "1", v.x, v.y, v.layer_to, v.drill)

    lines.append("999")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path
